
services:
  grafana:
    image: grafana/grafana:latest
    container_name: jabiseo-grafana
    restart: always
    ports:
      - "${GRAFANA_PORT:-4000}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - ../.env
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: jabiseo-prometheus
    restart: always
    env_file:
      - ../.env
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

volumes:
  grafana-data:
  prometheus-data:
