#-- 해당 부분은 override 하지 않으면 그대로 적용이 된다.


management:
  server:
    port: 9291
  endpoints:
    web:
      base-path: "/manage"
      exposure:
        include: health
  endpoint:
    health:
      show-components: always

firebase:
  key-path: "jabiseo-firebase-key.json"

notification:
  group-id: "notification-group"
  topic: "test" # @TODO secret + 원래 값 삽입 (다음 PR)

---
spring:
  config:
    activate:
      on-profile: notification-local

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: notification-dev
