#-- 해당 부분은 override 하지 않으면 그대로 적용이 된다.

oidc:
  kakao:
    issuer: ${KAKAO_ISSUER}
    admin-key: ${KAKAO_ADMIN_KEY}
    client-id: ${KAKAO_CLIENT_ID}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    issuer: ${GOOGLE_ISSUER}

jwt:
  access-expired-min: 60
  refresh-expired-day: 30
  refresh-key: ${REFRESH_KEY}
  access-key: ${ACCESS_KEY}

jabiseo:
  default-image-url: ${DEFAULT_IMAGE_URL}

management:
  server:
    port: 9292
  endpoints:
    web:
      base-path: "/manage"
      exposure:
        include: health
  endpoint:
    health:
      show-components: always

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

---
spring:
  config:
    activate:
      on-profile: api-local

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: api-dev


