services:

  filebeat:
    container_name: filebeat
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:8.15.0
    networks:
      - jabiseo-dev
    volumes:
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml"
      - logsVolume:/logs

  logstash:
    container_name: logstash
    hostname: logstash
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.9.0
    networks:
      - jabiseo-dev
    ports:
      - 5044:5044
    volumes:
      - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf"

volumes:
  logsVolume:
    external: true
    name: logsVolume

networks:
  jabiseo-dev:
    external: true
    name: jabiseo-dev
