# -- 기본으로 셋팅되는 값
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: ["localhost:29092"] # @TODO Secret 배포 전

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}

cloudfront:
  url: ${CLOUD_FRONT_URL}

opensearch:
    url: ${OPENSEARCH_URL}
    username: ${OPENSEARCH_USERNAME}
    password: ${OPENSEARCH_PASSWORD}


notification:
  group-id: "notification-group"
  topic: "test"
#  topic: "dev.jabiseo.plan-noti.json" # @TODO Secret

---
spring:
  config:
    activate:
      on-profile: "infra-local"

---
spring:
  config:
    activate:
      on-profile: "infra-dev"

  kafka:
    bootstrap-servers: [ "kafka:9092" ] # @TODO docker network 연결 후 커넥트
