name: "dev ci "

on:
  pull_request:
    types: [ opened ]
    branches:
      - "develop"
  workflow_dispatch:




jobs:
  gradle-docker-build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: CI start send message
        uses: jabiseo/slack-custom-bot@main
        with:
          mode: PR
          channelId: "${{ secrets.NOTI_CHANNEL_ID }}"
          text: "PullRequest 요청"
          statusColor: "#ebe834"
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "oracle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: gradle build
        run: |
          ./gradlew test -x bootJar


